name: CI-CD

on: [push]

jobs:
  build_linux_python_3_10:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ipywidgets-version: [7.6.4, 7.7.0, 8.1.0, 8.0.0, latest]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda install -y python=3.10

      - name: Install ipywidgets
        run: |
          if [ "${{ matrix.ipywidgets-version }}" = "latest" ]; then
            pip install ipywidgets
          else
            pip install ipywidgets==${{ matrix.ipywidgets-version }}
          fi

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          if [ "${{ matrix.ipywidgets-version }}" = "latest" ]; then
            pytest -vv --cov=mdonatello --cov-report=xml --cov-report=html --color=yes mdonatello/tests/
          else
            pytest mdonatello/tests/
          fi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
           token: ${{ secrets.CODECOV_TOKEN }}

  build_linux_python_3_11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ipywidgets-version: [8.1.0, 8.0.0, latest]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda install -y python=3.11

      - name: Install ipywidgets
        run: |
          if [ "${{ matrix.ipywidgets-version }}" = "latest" ]; then
            pip install ipywidgets
          else
            pip install ipywidgets==${{ matrix.ipywidgets-version }}
          fi

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          pytest mdonatello/tests/

  build_linux_python_3_12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ipywidgets-version: [8.1.0, 8.0.0, latest]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda install -y python=3.12

      - name: Install ipywidgets
        run: |
          if [ "${{ matrix.ipywidgets-version }}" = "latest" ]; then
            pip install ipywidgets
          else
            pip install ipywidgets==${{ matrix.ipywidgets-version }}
          fi

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          pytest mdonatello/tests/
