name: Windows_CI_CD

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        ipywidgets-version: [7.6.4, 7.7.0, 7.8.0, 8.0.0, 8.1.0, latest]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ipywidgets
        run: |
          if ($Env:ipywidgets-version -eq "latest") {
            pip install ipywidgets
          } else {
            pip install ipywidgets==$Env:ipywidgets-version
          }

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          pytest mdonatello/tests/
